name: Release on tag
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Get tag info
        id: tag
        run: |
          git fetch -f origin tag ${{ github.ref_name }}
          echo "msg=$(git tag -l --format='%(contents)' ${{ github.ref_name }})" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/uuideck.jar
            target/uuideck_completion
          body: ${{ steps.tag.outputs.msg }}
          generate_release_notes: true
          make_latest: legacy